import type { Metadata } from "next";
import { Reddit_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from '@/components/theme-provider';
import { ModeToggle } from '@/components/ui/mode-toggle';

const redditSans = Reddit_Mono({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Wing Stache App Denver",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body className={redditSans.className}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
          {children}
          <div>
            <ModeToggle />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
